name: Deploy Playground

on:
  push:
    branches: [main]

jobs:
  deploy-playground:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Build Playground
        run: |
          git config --global user.email "yosuke.kurami@gmai.com"
          git config --global user.name "Quramy"
          npm ci
          npm run build --workspace packages/playground
      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/playground/dist
