name: Deploy Playground

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy Playground
        run: |
          git config --global user.email "yosuke.kurami@gmai.com"
          git config --global user.name "Quramy"
          npm ci
          npm run build
          npx gh-pages -d dist
        working-directory: playground
        env:
          REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
